### ISSUE TITLE
Update iconset to v2.2

### ISSUE THREAD

**Issue by nanowang** [Angelmmiguel/material_icons#12]
https://github.com/google/material-design-icons/releases

**Comment by Angelmmiguel** [comment]
I will update to the last release of [Material Design icons](https://github.com/google/material-design-icons/releases/tag/2.2.1).

**Comment by Angelmmiguel** [comment]
There is a new release: [v2.2.2](https://github.com/google/material-design-icons/releases/tag/2.2.2)

**Comment by Angelmmiguel** [comment]
Done. I update the version of the gem to [v2.2.0](https://github.com/Angelmmiguel/material_icons/releases/tag/v2.2.0). Thanks for advice me a new version of Google Design Icons :)
