### ISSUE TITLE
Send icon causes error: no method name given

### ISSUE THREAD

**Issue by fwoelm** [Angelmmiguel/material_icons#15]
When calling `<%= material_icon.send %>`, Rails throws the error `no method name given`. I assume this is [because `send` is a pre-defined Rails method for classes](https://ruby-doc.org/core-2.3.1/Object.html#method-i-send).

It might be necessary to "encode" the name of the send icon, similar to how it was done for three_d_rotation.

**Comment by Angelmmiguel** [comment]
Hello @fwoelm,

Yes, you are right, `send` is a predefined method for classes. I was thinking in override this method. If the method receives some param, I can call the real `send`. In the other case, I can set the icon to send.
