### ISSUE TITLE
Any plans on extending this to include more materialize components?

### ISSUE THREAD

**Issue by bo-oz** [Angelmmiguel/material_icons#23]
I'm actually looking to refactor my app's templates and noticed that the materialize CSS structure is causing a lot of repetition. So I was looking for some kind of Rails helper. This repo is the only thing I found so far, any plans on extending this to include other components? Could you elaborate a bit on how you think this could be structured? Would love to help!

**Comment by bo-oz** [comment]
I just realized this gem is aimed at Google Material icons, sorry for the confusion, thought it was for Materialize CSS.

**Comment by Angelmmiguel** [comment]
np! Have a nice day 😄
