### ISSUE TITLE
Calendar_today icon

### ISSUE THREAD

**Issue by vassilis** [Angelmmiguel/material_icons#30]
The calendar_today icon looks broken as it renders with about 200px padding on the left side.

I wasn't able to fix it with CSS.

![screenshot](https://user-images.githubusercontent.com/363465/53005724-7a892080-343c-11e9-9c0c-45ed19bb7314.png)

**Comment by Angelmmiguel** [comment]
Hello @vassilis,

Thank you for submitting the issue! Please, could you provide me the code you're using to render that icon? I'm gonna try to reproduce your issue in my environment.

Thanks!

**Comment by MaksJS** [comment]
:+1:

**Comment by myin142** [comment]
This is a bug in https://github.com/google/material-design-icons/issues/302
