### ISSUE TITLE
Why is sqlite3 marked as a dependency? 

### ISSUE THREAD

**Issue by FabricioPavano** [Angelmmiguel/material_icons#31]

**Comment by Angelmmiguel** [comment]
Hello @FabricioPavano,

Sqlite3 is added for [testing purposes](https://github.com/Angelmmiguel/material_icons/blob/master/material_icons.gemspec#L19). I use a [dummy Rails application](https://github.com/Angelmmiguel/material_icons/tree/master/spec/dummy) for testing the icons and helpers in the views.

**Comment by Angelmmiguel** [comment]
I'm going to close this issue. Please, open it again in case you've another question :)
