### ISSUE TITLE
Logout icon not working

### ISSUE THREAD

**Issue by hoghug** [Angelmmiguel/material_icons#35]
Logout icon doesn't appear when calling it. 
`<%= mi.logout %>`
`<span class="material-icons">logout</span>`

**Comment by Angelmmiguel** [comment]
Thank you for the report @hoghug and sorry for the long delay. There's a task to update the Material Icons versions which I assume will fix this issue.

This will be released as v4.0.0

**Comment by Angelmmiguel** [comment]
This is fixed on the new v4.0.0 version of the gem! It includes all the new styles as well as other improvements. Here you can find all the release notes :) https://github.com/Angelmmiguel/material_icons/releases/tag/v4.0.0
