### ISSUE TITLE
Helper not html_safe

### ISSUE THREAD

**Issue by kurtisnelson** [Angelmmiguel/material_icons#4]
If you use the helper, it's output is not marked HTML safe.

**Comment by Angelmmiguel** [comment]
Hello,

When you use the helper, it returns an instance of [MaterialIcon](https://github.com/Angelmmiguel/material_icons/blob/master/app/models/material_icon.rb) model. When render it into the view, [to_s](https://github.com/Angelmmiguel/material_icons/blob/master/app/models/material_icon.rb#L102-L118) method is called. This method use `content_tag`, a helper provided by ActionView. Returned string of this method is `html_safe`, as you can see in [ActionView::Helpers::TagHelper line 137](https://github.com/rails/rails/blob/4-1-stable/actionview/lib/action_view/helpers/tag_helper.rb#L137).

**Comment by kurtisnelson** [comment]
I have to use a double equals though.

**Comment by Angelmmiguel** [comment]
What do you mean with double equals @kurtisnelson?

**Comment by kurtisnelson** [comment]
In slim, a == overrides html_safe and doesn't escape the string. If I use
=, I end up with HTML on the page.

**Comment by Angelmmiguel** [comment]
I still don't understand where do you use double equals and equals methods. They are different completely. Can you explain more your problem?

Please, add more info about variables you use, initialization of them... And a piece of code that show your problem.

Thanks!

**Comment by Angelmmiguel** [comment]
I not received any update in this issue from ten days ago. I will close it. If you need more help on this issue or another, please reopen this or create a new one. Thanks!
