### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by hawkes69** [Angelmmiguel/material_icons#45]
@Angelmmiguel I know there was [this pull request](https://github.com/Angelmmiguel/material_icons/pull/36) earlier to add missing icons but I'm still missing a lot. When I try to use the ones I find at the [official site](https://fonts.google.com/icons?selected=Material+Icons). For example `key_off`, `psychology_alt`, and `task_alt` are all missing. Also, I noticed some icons don't seem to match what shows on the official site. For example, the `android` icon shows the full android robot in implementation but on the official site, it just shows the android head. Am I looking in the wrong spot for icons? Or is the current font library not pulling in all the fonts? Any help is much apprecciated.

**Comment by bago2k4** [comment]
Guys any update on this? I am experiencing the same, for example `science` is missing on the web version. Also all the `outlined` versions don't work.
Thanks

**Comment by Angelmmiguel** [comment]
Hello @bago2k4 and @hawkes69,

I'm sorry but I've been quite busy these months. I will try to close these issues. It's still in my mind, but I couldn't find the time to complete them.

I will try to close it in the upcoming weeks :)

**Comment by Angelmmiguel** [comment]
This is fixed on the new v4.0.0 version of the gem! It includes all the new styles as well as other improvements. Here you can find all the release notes :) https://github.com/Angelmmiguel/material_icons/releases/tag/v4.0.0
