### ISSUE TITLE
First time icon not working proper in safari

### ISSUE THREAD

**Issue by dineshpandianr** [Angelmmiguel/material_icons#5]

**Comment by Angelmmiguel** [comment]
Hello,

I need some information about the bug to reproduce it. 

* Are you using `MaterialIcon` helper? 
* Does the problem appear selecting any icon or one in particular?
* Ruby and Rails version.

Thanks you for open an issue.

**Comment by dineshpandianr** [comment]
Hi,

Thanks for replying. I'm using safari Version 9.0 and Rails 4.2.3, I install the gem and Required the CSS, its working perfectly in other browsers, but in safari first when I load for the first time it doesn't work, after hard refresh it works

**Comment by Angelmmiguel** [comment]
Thanks, I will review your problem and try to reproduce in my environment.

**Comment by Angelmmiguel** [comment]
I'm trying to reproduce the problem:

* Create a new project with Rails 4.2.3
* Require Material Icons gem and use it in ligatures mode
* Insert some icons in a view
* Open the view in Safari 9.0 (11601.1.56)
* Restart the server with the gem in unicode mode
* Close safari and open it.

To test I use web-brick server.

In both cases, the icons are displayed on first load. Can you see Element Inspector of Safari to check if the font is loaded?

**Comment by Angelmmiguel** [comment]
There isn't any recent activity in this issue. I will close it, but if you need more help, reopen it :).

Thanks!
