### ISSUE TITLE
Method name conflict with the icon `style`

### ISSUE THREAD

**Issue by nanowang** [Angelmmiguel/material_icons#8]
Yep there's an icon named `style`.

**Comment by Angelmmiguel** [comment]
I don't saw it :fearful:. I think three solutions to solve this problem:

1. Update the name of `style` method. This option breaks retro compatibility with `material_icon` helper.
2. Change the name of the icon in the gem. It can be confused, and I need to notify it in README.
3. Create a new method called `icon` and don't use `method_missing` to get the name of the icon. This solution breaks retro compatibility, but with an `icon` method I prevent similar future problems.

I like the first and third solution; I will think it some time.

Thanks for report the issue!

**Comment by pikislabis** [comment]
If you want to still use `method_missing`, you can distinguish when you are trying to use style icon (no parameters) or style method (using parameters).

**Comment by Angelmmiguel** [comment]
Thanks, @pikislabis. I like your solution, and I will implement it in the gem.

However, I think I will create an `icon` method for a future release. In this case, `style` method receives parameters, but another cases like `flip_vertical` could be a problem.

**Comment by Angelmmiguel** [comment]
Fixed in 2.0.1 version. Thanks :)
