### ISSUE TITLE
View helper is not html safe

### ISSUE THREAD

**Issue by romaslmd** [Angelmmiguel/material_icons#9]
Hi,
found this thing recently:
```
rails (4.2.1)
material_icons (2.0.1)
bootstrap-material-design (0.2.2)
```
(note: only on production env)
`RAILS_ENV=production`

```
# views/.../_action.html.slim
button.btn[type="submit"]
  = material_icon.search.md_18
```

output was a link with raw inner html as text

```
<button class="btn" type="submit"><i class="material-icons md-18 ">search</i></button>
```
but with

```
# views/.../_action.html.slim
button.btn[type="submit"]
    = material_icon.search.md_18.to_s.html_safe
```
all worked fine.

**Comment by Angelmmiguel** [comment]
Hello @romaslmd,

When you use the helper, it returns an instance of [MaterialIcon](https://github.com/Angelmmiguel/material_icons/blob/master/app/models/material_icon.rb) model. When to render it into the view, [to_s](https://github.com/Angelmmiguel/material_icons/blob/master/app/models/material_icon.rb#L108) method is called. This method uses `content_tag`, a helper provided by ActionView. Returned string of this method is html_safe, as you can see in [ActionView::Helpers::TagHelper line 146](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/tag_helper.rb#L146).

The problem can come from `Slim` template engine, I will check it. Can you tell me the version of Slim?

Thanks!

**Comment by romaslmd** [comment]
```
slim (3.0.6)
```

**Comment by romaslmd** [comment]
@Angelmmiguel 
U r right, problem related to `Slim`.
probably best option is to use double equal sign in view:
```
== material_icon.search
```

**Comment by Angelmmiguel** [comment]
Okey @romaslmd. I will close this issue and add a section in `README`. However, I will investigate it to report this if it's a `Slim` bug.

Thanks!

**Comment by Angelmmiguel** [comment]
Added to Readme.
